name: Publish Docker image

on:
  schedule:
    - cron: '0 0 * * *'  # Once a day at midnight.
  push:
    branches:
      - main
    paths:
      # Workflow file itself
      - '.github/workflows/deploy.yml'
      # Dockerfile
      - '**/Dockerfile'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - { name: "ubuntu-22.04:gcc-13",  path: "Ubuntu/22.04/gcc-13", platforms: "linux/amd64" }

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ matrix.image.path }}
          push: true
          pull: true
          platforms: ${{ matrix.image.platforms }}
          tags: |
            ams21/${{ matrix.image.name }}
            ghcr.io/ams21/${{ matrix.image.name }}
